### ISSUE TITLE
Question about the results

### ISSUE THREAD

**Issue by mandal4** [dohoseok/SGRN_torch#2]
First, thanks for sharing the code! 
I have a question about the results.
 
_Faster RCNN Mean Average Precision : 11.2
Faster RCNN with SGRN Mean Average Precision : 11.5_

I wonder if the results are based on

1) VG_1000 test set
2) res101 backbone without **FPN**
3) mAP is over iou threshold 0.5 **(mAP@0.5)**

Thanks :)

**Comment by dohoseok** [comment]
1. yes
2. I did not test with FPN
3. yes
