### ISSUE TITLE
Ask about some logic in implementation

### ISSUE THREAD

**Issue by mandal4** [dohoseok/SGRN_torch#3]
Thanks for sharing the implementation code.
I have some question about the logic in your implementation.
In the lines (448~452) from [lib/nets/network_gcn.py](https://github.com/dohoseok/SGRN_torch/blob/master/lib/nets/network_gcn.py) 

`        cls_pred = torch.max(cls_prob, 1)[1]
        bbox_pred_reshape = bbox_pred.view(-1, 1001, 4)
        bbox_pred_cls = torch.zeros(num_rois, 4)
        for i, cls in enumerate(cls_pred):
            bbox_pred_cls[i] = bbox_pred_reshape[i][cls]`, 
Coordinates are sampled among rois with respect to class that represent max score. But there is no bbox regressor for background, and given the background roi, we couldn't sample the coordinates of the roi.
Formally, i wonder how this logic run even though length of cls_prob is **number of class+1** but, length of bbox_pred_reshape.size(0) is supposed to be **number of class**  

I couldn't run this code to check it as memory capacity problem. Thanks again for sharing your work.

**Comment by dohoseok** [comment]
The value of self._num_classes is 1001.
it is set from lines(35~41) of lib/datasets/visual_genome.py
First class is 'background' in this code.
