### ISSUE TITLE
Question about the experimental results

### ISSUE THREAD

**Issue by mandal4** [dohoseok/SGRN_torch#5]
Thx for the code.
Do you have experimental result on MSCOCO? 
I train the SGRN(based on your code) with MSCOCO, but there was no mAP increase from FasterRCNN

Thanks again for sharing the code.

**Comment by dohoseok** [comment]
I only experimented with VisualGenome Dataset.

**Comment by okluckychen** [comment]
TvT....There was no mAP increase from FasterRCNN on my own datasets(VOC2007 format) either.

**Comment by Wyman-yang** [comment]
> TvT....There was no mAP increase from FasterRCNN on my own datasets(VOC2007 format) either.

Are you working on GCN in Object Detection? I have tried to reproduce many related papers, but still cannot get a good mAP improvements...How about you?

**Comment by okluckychen** [comment]
> Are you working on GCN in Object Detection

Yes,I am still working on it,are you interested in this work too?Do you have a Wechat ID?Maybe we can discuss further.

**Comment by Wyman-yang** [comment]
> > Are you working on GCN in Object Detection
> 
> Yes,I am still working on it,are you interested in this work too?Do you have a Wechat ID?Maybe we can discuss further.

SURE, I am working on this too, my Wechat ID is huhu19980526

**Comment by mandal4** [comment]
> > > Are you working on GCN in Object Detection
> > 
> > 
> > Yes,I am still working on it,are you interested in this work too?Do you have a Wechat ID?Maybe we can discuss further.
> 
> SURE, I am working on this too, my Wechat ID is huhu19980526

Hello, i am working on this kind approach too, i will contact you too on Wechat!

**Comment by Wyman-yang** [comment]
> > > > Are you working on GCN in Object Detection
> > > 
> > > 
> > > Yes,I am still working on it,are you interested in this work too?Do you have a Wechat ID?Maybe we can discuss further.
> > 
> > 
> > SURE, I am working on this too, my Wechat ID is huhu19980526
> 
> Hello, i am working on this kind approach too, i will contact you too on Wechat!

Have you contacted me？

**Comment by mandal4** [comment]
> > > > > Are you working on GCN in Object Detection
> > > > 
> > > > 
> > > > Yes,I am still working on it,are you interested in this work too?Do you have a Wechat ID?Maybe we can discuss further.
> > > 
> > > 
> > > SURE, I am working on this too, my Wechat ID is huhu19980526
> > 
> > 
> > Hello, i am working on this kind approach too, i will contact you too on Wechat!
> 
> Have you contacted me？

I have tried it but failed to sign up at Wechat.. T^T
Could you tell me your email address? we can contact from that!

**Comment by Wyman-yang** [comment]
> > > > > > Are you working on GCN in Object Detection
> > > > > 
> > > > > 
> > > > > Yes,I am still working on it,are you interested in this work too?Do you have a Wechat ID?Maybe we can discuss further.
> > > > 
> > > > 
> > > > SURE, I am working on this too, my Wechat ID is huhu19980526
> > > 
> > > 
> > > Hello, i am working on this kind approach too, i will contact you too on Wechat!
> > 
> > 
> > Have you contacted me？
> 
> I have tried it but failed to sign up at Wechat.. T^T
> Could you tell me your email address? we can contact from that!

wymanbest@outlook.com
